#ansible_ssh_common_args: "{% if 'bastion' in groups['all'] %} -o ProxyCommand='ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -W %h:%p {{ hostvars['bastion']['ansible_user'] }}@{{ hostvars['bastion']['ansible_host'] }} {% if ansible_ssh_private_key_file is defined %}-i {{ ansible_ssh_private_key_file }}{% endif %} ' {% endif %}"
- hosts: k8s-cluster:children
  gather_facts: false
  roles:
    - { role: ssh}
  become: yes
  become_user: root
  tasks:
  - name: ansible create certs directory
    file:
      path: /etc/kubernetes/ssl
      state: directory

  - name: Copy the CA TLS cert to the kubernetes nodes
    copy:
      src: "{{ lookup('env','OS_CACERT') }}"
      dest: /etc/kubernetes/ssl/openstack-tls-ca.crt
      owner: root
      group: root
      mode: 0644